import { collection, doc, setDoc, serverTimestamp, getDocs, query, where, orderBy } from "firebase/firestore";
import { db } from "./firebase";

// Schema Definitions
export interface MediaMetadata {
  id: string;              // Custom generated or Firestore native ID
  uploaderId: string;      
  uploaderName: string;
  school?: string;         // Optional context mapping
  isPrivate: boolean;      // True = Private Vault, False = Live Feed
  fileUrls: string[];      // Array of URLs (from storage.ts)
  description?: string;
  aiTags: string[];        // Generated by Gemini API
  timestamp: any;          // Firebase serverTimestamp
}

export interface PublishedEvent {
  id?: string;
  title: string;           // 5 word limit generated by Gemini
  description: string;     // 2 sentence generated by Gemini
  coverPhotoUrl: string;
  galleryUrls: string[];
  timestamp: any;
}

/**
 * Saves generic media documents to Firestore. 
 */
export async function saveMediaMetadata(metadata: Partial<MediaMetadata>, customId?: string) {
  const metaObj = {
    ...metadata,
    timestamp: serverTimestamp(),
  };

  if (customId) {
    const docRef = doc(db, "media_assets", customId);
    await setDoc(docRef, metaObj);
    return customId;
  } else {
    // Let Firestore trigger auto-ID
    const colRef = collection(db, "media_assets");
    const docRef = doc(colRef);
    await setDoc(docRef, { ...metaObj, id: docRef.id });
    return docRef.id;
  }
}

/**
 * Retrieves a user's private media
 */
export async function getPrivateUserMedia(userId: string) {
  const colRef = collection(db, "media_assets");
  const q = query(
    colRef,
    where("uploaderId", "==", userId),
    where("isPrivate", "==", true),
    orderBy("timestamp", "desc")
  );
  
  const snap = await getDocs(q);
  return snap.docs.map((doc) => doc.data() as MediaMetadata);
}

/**
 * Publishes a curated event for the statically deployed website to consume.
 */
export async function savePublishedEvent(event: Partial<PublishedEvent>) {
  const docRef = doc(collection(db, "published_events"));
  const publishObj = {
    ...event,
    id: docRef.id,
    timestamp: serverTimestamp(),
  };
  await setDoc(docRef, publishObj);
  return docRef.id;
}
